// <auto-generated />
using System;
using ConnectorAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConnectorAPI.Migrations
{
    [DbContext(typeof(ConnectorDbContext))]
    [Migration("20240119014307_Index_Column")]
    partial class Index_Column
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConnectorAPI.DbContexts.ConnectorDb.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessorNode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DBConnectionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerNode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerNode", "AccessorNode");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("ConnectorAPI.DbContexts.ConnectorDb.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ResourceTableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("connectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("ResourceName");

                    b.HasIndex("connectionId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("ConnectorAPI.DbContexts.ConnectorDb.ResourceAttributes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttributeColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("MinimumAccessLevel")
                        .HasColumnType("smallint");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("ConnectorAPI.DbContexts.ConnectorDb.Resource", b =>
                {
                    b.HasOne("ConnectorAPI.DbContexts.ConnectorDb.Connection", "connection")
                        .WithMany("sharedResources")
                        .HasForeignKey("connectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("connection");
                });

            modelBuilder.Entity("ConnectorAPI.DbContexts.ConnectorDb.ResourceAttributes", b =>
                {
                    b.HasOne("ConnectorAPI.DbContexts.ConnectorDb.Resource", "Resource")
                        .WithMany("Attributes")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("ConnectorAPI.DbContexts.ConnectorDb.Connection", b =>
                {
                    b.Navigation("sharedResources");
                });

            modelBuilder.Entity("ConnectorAPI.DbContexts.ConnectorDb.Resource", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
